export const PRODUCT_ACTIONS = {
  PUBLISH: 'publish',
  UNPUBLISH: 'unpublish',
};

export const PRODUCT_STATUSES = {
  PUBLISHED: 'published',
  UNPUBLISHED: 'unpublished',
  MODIFIED: 'modified',
};

export const FILTER_TYPES = {
  lessThan: 'lessThan',
  moreThan: 'moreThan',
  equalTo: 'equalTo',
  range: 'range',
  missing: 'missing',
  missingIn: 'missingIn',
  in: 'in',
};

export const INITIALIZE_SEARCH_SLICE = 'INITIALIZE_SEARCH_SLICE';
export const SET_SEARCH_FILTER_STATE = 'SET_SEARCH_FILTER_STATE';
export const SET_SEARCH_FILTER_RESULT = 'SET_SEARCH_FILTER_RESULT';
export const REMOVE_ENTITY_BY_ID_FROM_SEARCH_RESULTS =
  'REMOVE_ENTITY_BY_ID_FROM_SEARCH_RESULTS';

export const FIELD_TYPES = {
  Money: 'Money',
  LocalizedString: 'LocalizedString',
  Time: 'Time',
  DateTime: 'DateTime',
  Boolean: 'Boolean',
  String: 'String',
  Enum: 'Enum',
  LocalizedEnum: 'LocalizedEnum',
  Number: 'Number',
  Date: 'Date',
  Reference: 'Reference',
  Set: 'Set',
};

export const permissions = {
  ViewCustomerGroups: 'ViewCustomerGroups',
  ViewStates: 'ViewStates',
};

export const QUERY_MAX_LIMIT = 500;
// PRODUCT_PROJECTION
export const PRODUCT_SET_DRAFT = 'PRODUCT_SET_DRAFT';
export const MODIFIED_PRODUCTS_FETCHED = 'MODIFIED_PRODUCTS_FETCHED';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_UPDATED_WITH_IMAGE_UPLOAD =
  'PRODUCT_UPDATED_WITH_IMAGE_UPLOAD';
export const PRODUCT_IMAGE_UPLOADED = 'PRODUCT_IMAGE_UPLOADED';
export const PRODUCT_SET_CHECK_SELECTION = 'PRODUCT_SET_CHECK_SELECTION';
export const PRODUCT_SET_ALL_CHECK_SELECTION =
  'PRODUCT_SET_ALL_CHECK_SELECTION';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const SET_VISIBLE_PRODUCT = 'SET_VISIBLE_PRODUCT';
export const PRODUCT_STATE_TRANSITIONED = 'PRODUCT_STATE_TRANSITIONED';
export const PRODUCTS_DELETED_IN_LIST = 'PRODUCTS_DELETED_IN_LIST';
export const PRODUCT_MASTER_VARIANT_CHANGED = 'PRODUCT_MASTER_VARIANT_CHANGED';
// PRODUCT_TYPE_SETTINGS
export const PRODUCT_TYPE_SETTINGS_FETCHED = 'PRODUCT_TYPE_SETTINGS_FETCHED';
export const PRODUCT_TYPE_SETTINGS_CHANGED = 'PRODUCT_TYPE_SETTINGS_CHANGED';
export const PRODUCT_TYPE_SETTINGS_DELETED = 'PRODUCT_TYPE_SETTINGS_DELETED';
// PRODUCT VIEW
export const SET_VIEW_MODE = 'SET_VIEW_MODE';
export const VIEW_MODES = {
  PRODUCTS_LIST: 'PRODUCTS_LIST',
  BULK_UPDATE: 'BULK_UPDATE',
};

// PRODUCT_SETTINGS
export const ADD_PRODUCT_LIST_VIEW_SETTINGS_TO_LIST =
  'ADD_PRODUCT_LIST_VIEW_SETTINGS_TO_LIST';
export const REMOVE_PRODUCT_LIST_VIEW_SETTINGS_FROM_LIST =
  'REMOVE_PRODUCT_LIST_VIEW_SETTINGS_FROM_LIST';
export const SET_PRODUCT_LIST_VIEW_SETTINGS_LIST =
  'SET_PRODUCT_LIST_VIEW_SETTINGS_LIST';
export const SET_ACTIVE_PRODUCT_LIST_VIEW_SETTINGS =
  'SET_ACTIVE_PRODUCT_LIST_VIEW_SETTINGS';

// ATTRIBUTE CONSTRAINTS

export const ATTRIBUTE_CONSTRAINTS = {
  SAME_FOR_ALL: 'SameForAll',
  NONE: 'None',
  UNIQUE: 'Unique',
  COMBINATION_UNIQUE: 'CombinationUnique',
};

// STATES
export const INITIAL_PRODUCT_STATES_FETCHED = 'INITIAL_PRODUCT_STATES_FETCHED';
export const PRODUCT_STATES_FETCHED = 'PRODUCT_STATES_FETCHED';
// PRODUCT SEARCH AND FILTER
export const PRODUCT_SEARCH_TEXT = 'filter_text';
export const PRODUCT_SEARCH_SORTING = 'list_sorting';
export const PRODUCT_SEARCH_PAGE = 'list_page';
export const PRODUCT_SEARCH_FILTER_PRODUCT_TYPE = 'filter_productTypes';
export const PRODUCT_SEARCH_FILTER_ATTRIBUTES = 'filter_customAttributes';
export const PRODUCT_SEARCH_FILTER_CATEGORIES = 'filter_categories';
export const PRODUCT_SEARCH_FILTER_STATUS = 'filter_status';
export const PRODUCT_SEARCH_FILTER_STATES = 'filter_states';
export const PRODUCT_SEARCH_FILTER_MISSING = 'filter_missing';
export const PRODUCT_SEARCH_FILTERS_VISIBLE = 'filter_tags_visible';
export const PRODUCT_SEARCH_FILTERS_EXCLUDE_SUBCATEGORIES =
  'filter_exclude_subcategories';
// PRODUCT_TYPES
export const PRODUCT_TYPES_FETCHED = 'PRODUCT_TYPES_FETCHED';
export const PRODUCT_TYPE_FETCHED = 'PRODUCT_TYPE_FETCHED';
export const PRODUCT_TYPE_CREATED = 'PRODUCT_TYPE_CREATED';
export const PRODUCT_TYPE_DELETED = 'PRODUCT_TYPE_DELETED';
export const PRODUCT_TYPES_FOR_FILTER_FETCHED =
  'PRODUCT_TYPES_FOR_FILTER_FETCHED';
export const PRODUCT_TYPES_FOR_ATTRIBUTES_FETCHED =
  'PRODUCT_TYPES_FOR_ATTRIBUTES_FETCHED';
// RECOMMENDED_CATEGORIES
export const RECOMMENDED_CATEGORIES_FETCHED = 'RECOMMENDED_CATEGORIES_FETCHED';
export const RECOMMENDED_CATEGORIES_STATUS = 'RECOMMENDED_CATEGORIES_STATUS';
export const RECOMMENDED_CATEGORIES_SEARCH_PROPERTIES = {
  Attribute: 'Attribute',
  MachineLearning: 'MachineLearning',
  ProductType: 'ProductType',
};
export const RECOMMENDED_CATEGORIES_STATUS_TYPE = {
  ON: 'on',
  OFF: 'off',
  PROCESSING: 'processing',
};
// PRODUCT BULK UPDATES
export const START_BULK_UPDATE = 'BULK_START_BULK_UPDATE';
export const ADD_BULK_UPDATE_SUCCESS = 'BULK_ADD_BULK_UPDATE_SUCCESS';
export const ADD_BULK_UPDATE_FAILURE = 'BULK_ADD_BULK_UPDATE_FAILURE';
export const BULK_NEXT_STEP = 'BULK_NEXT_STEP';
export const BULK_SET_SELECTED_ATTRIBUTES = 'BULK_SET_SELECTED_ATTRIBUTES';
export const BULK_TOGGLE_CONFIRMATION_DIALOG =
  'BULK_TOGGLE_CONFIRMATION_DIALOG';
export const BULK_LEAVE_BULK_UPDATE = 'BULK_LEAVE_BULK_UPDATE';
