const initialValues = {
  firstName: '',
  lastName: '',
  phone: '',
  mobile: '',
  fax: '',
  email: '',
  company: '',
  streetName: '',
  streetNumber: '',
  city: '',
  postalCode: '',
  pOBox: '',
  building: '',
  apartment: '',
  region: '',
  country: '',
  state: '',
  department: '',
  title: '',
  salutation: '',
  additionalStreetInfo: '',
};

export default initialValues;
