export const SEARCH_SLICE_NAME_CUSTOMER_GROUPS =
  'SEARCH_SLICE_NAME_CUSTOMER_GROUPS';
export const SEARCH_SLICE_NAME_CUSTOMER_ORDERS =
  'application-customers/SEARCH_SLICE_NAME_CUSTOMER_ORDERS';

export const SEARCH_SLICE_NAME_COMPANY_EMPLOYEES =
  'application-customers/SEARCH_SLICE_NAME_COMPANY_EMPLYEES';
